<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTkvmYvq\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTkvmYvq/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTkvmYvq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTkvmYvq\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTkvmYvq\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TkvmYvq',
    'container.build_id' => '97857ae8',
    'container.build_time' => 1646482503,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTkvmYvq');
