<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2sCyMtH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2sCyMtH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2sCyMtH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2sCyMtH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2sCyMtH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2sCyMtH',
    'container.build_id' => '29b6a5f2',
    'container.build_time' => 1646485716,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2sCyMtH');
